### ISSUE TITLE
Misleading documentation about sorting.

### ISSUE THREAD

**Issue by darkowlzz** [orchestrate-io/porc#11]
The sample code for sorting provided [here] is misleading.
I suggest it should be something like:
```python
pages = client.search('cafes', 'value.location:NEAR:{lat:... lon:... dist:1mi}', sort='value.location:distance:asc')
```

[here]: https://github.com/orchestrate-io/porc#clientsearch

**Comment by dizzyd** [comment]
This PR was merged. Marking as complete.
